"""init_schema

Revision ID: 18f9bd9c8751
Revises: 
Create Date: 2026-01-01 20:04:48.076387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '18f9bd9c8751'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.Column('thumbnail_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('is_known', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faces_name'), 'faces', ['name'], unique=False)
    op.create_table('stream_configs',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rtsp_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('whisper_enabled', sa.Boolean(), nullable=False),
    sa.Column('face_detection_enabled', sa.Boolean(), nullable=False),
    sa.Column('face_detection_interval', sa.Integer(), nullable=False),
    sa.Column('save_transcripts_to_file', sa.Boolean(), nullable=False),
    sa.Column('transcript_file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('audio_energy_threshold', sa.Float(), nullable=True),
    sa.Column('audio_vad_enabled', sa.Boolean(), nullable=True),
    sa.Column('audio_vad_threshold', sa.Float(), nullable=True),
    sa.Column('audio_vad_onset', sa.Float(), nullable=True),
    sa.Column('audio_vad_offset', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_configs_name'), 'stream_configs', ['name'], unique=False)
    op.create_table('face_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('face_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('snapshot_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('face_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['face_id'], ['faces.id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['stream_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_events_stream_id'), 'face_events', ['stream_id'], unique=False)
    op.create_index(op.f('ix_face_events_timestamp'), 'face_events', ['timestamp'], unique=False)
    op.create_table('transcripts',
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('speaker_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stream_id'], ['stream_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_created_at'), 'transcripts', ['created_at'], unique=False)
    op.create_index(op.f('ix_transcripts_stream_id'), 'transcripts', ['stream_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcripts_stream_id'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_created_at'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_face_events_timestamp'), table_name='face_events')
    op.drop_index(op.f('ix_face_events_stream_id'), table_name='face_events')
    op.drop_table('face_events')
    op.drop_index(op.f('ix_stream_configs_name'), table_name='stream_configs')
    op.drop_table('stream_configs')
    op.drop_index(op.f('ix_faces_name'), table_name='faces')
    op.drop_table('faces')
    # ### end Alembic commands ###
