"""upgrade_face_recognition

Revision ID: efc7653464cf
Revises: a1b2c3d4e5f6
Create Date: 2026-01-02 14:50:43.523705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'efc7653464cf'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('face_id', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['face_id'], ['faces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('face_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_face_embeddings_face_id'), ['face_id'], unique=False)

    with op.batch_alter_table('faces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('avg_embedding', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faces', schema=None) as batch_op:
        batch_op.drop_column('avg_embedding')
        batch_op.drop_column('embedding_count')

    with op.batch_alter_table('face_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_face_embeddings_face_id'))

    op.drop_table('face_embeddings')
    # ### end Alembic commands ###
